### ISSUE TITLE
이미지 확대 기능 추가

### ISSUE THREAD

**Issue by skssms** [ondisplay/collected-issues#1]
부스 페이지, 작품 목록 페이지, 작품상세 페이지에서 제대로된 작품 이미지 확대 기능을 추가할 때가 되었습니다..!!!

고화질 작품 이미지를 확대해서 볼 수 있는 기능은 작품 구매에 있어서 필수적인 기능일 거라고 생각해요.

지난번 정현님과 이야기에서 나온 것들 정리해보면

- pin to zoom 기능 넣기
- 버튼으로 다음, 이전 사진 넘기기 (loop로 할건지? 현재 몇 번째 보고 있는지 알려주기)
- 던져서 끄기 기능은 빼기
- 데스크톱에서는 좀 다르게 쓰기 (max width, height 있는 모달 추천)

정도로 정리 되는 것 같네요

**Comment by ghost** [comment]
features roadmap Ideas로 추가함
https://trello.com/c/74dhDBaW
