### ISSUE TITLE
작가의 작품 목록에서 판매 완료, 판매 불가인 작품들이 맨 앞에 노출됩니다.

### ISSUE THREAD

**Issue by ghost** [ondisplay/collected-issues#15]
보통 판매 완료, 판매 불가인 작품들을 맨 마지막에 등록하는데 그러면 작가의 작품 목록이 가장 앞에 등장합니다.

작가 페이지 뿐만 아니라 작품 상세 페이지의 "이 작가의 다른 작품" 기능에서도 마찬가지 입니다.

작가 페이지에서 작품 노출 순서를 변경 가능하게 하거나, 그렇지 않더라도 판매 완료, 판매 불가인 것들을 자동으로 뒤로 미뤘으면 좋겠습니다.

**Comment by ghost** [comment]
작품 노출 순서를 한 번 더 지정해주기 보다는 판매 완료, 판매 불가인 작품을 맨 뒤로 보내는 방식으로 해결하는 것이 더 낫겠다고 CD님들과 상의함.

작품 상세 페이지의 "이 작가의 다른 작품" 에서는 작가의 작품 볼 때마다 다르게 보여주기보다는 해당 작품의 다음 순번부터 보여준다던지, 아니면 랜덤으로 보여준다던지 해서 계속 다른 작품을 보여주는 방식도 고려해볼만 하다.

**Comment by ghost** [comment]
Features Roadmap으로 추가.

https://trello.com/c/CLxtfaF9
https://trello.com/c/QuESRgn6

**Comment by kayk1m** [comment]
작품 상세 페이지 "이 작가의 다른 작품" 판매중인 작품 중 랜덤 노출하고 판매중인 작품수가 부족하면 판매불가, 판매완료 작품 노출.

**Comment by kayk1m** [comment]
https://test.ondp.app/
에 반영 완료
