### ISSUE TITLE
작품정보 - 작품설명을 추가 문제

### ISSUE THREAD

**Issue by kkrkdtks** [ondisplay/collected-issues#22]
https://collected.ondp.app/booth/0r6jDdkQ2Zs3ragkVobM/artworks

작품목록에서 작품을 하나씩 보기를 선택하면
작품 설명 1줄이 보이고, 더보기가 나타나야합니다.

하지만 처음 작품을 올릴 때 작품설명을 넣지 않고 작품을 저장하고 난 뒤
이후 수정으로 설명을 추가하면 첨부 사진과 같이 설명이 보이지 않네요.

![1111111111114](https://user-images.githubusercontent.com/83440182/117237236-743cbe80-ae65-11eb-9872-bd91563d7d17.PNG)

![222222222](https://user-images.githubusercontent.com/83440182/117237049-06909280-ae65-11eb-9408-e7bf40c9c1d9.PNG)

**Comment by ghost** [comment]
예리하시군요..

**Comment by kayk1m** [comment]
실시간 반영이 안되어서 그래요. 새로고침하면 적용됩니다.
