### ISSUE TITLE
본문 글자수 세기 기능 추가를 원해요

### ISSUE THREAD

**Issue by ekf1121** [ondisplay/collected-issues#32]
이전에는 노션에서 원고를 쓰고, 최종적으로 완성한 후에 컬렉티드로 옮겼지만
현재는 업로드 페이지가 안정화되면서 노션은 거의 안쓰고 있어요.
바로 긁어서 복붙하면 됐지만ㅠ 본문글이 박스로 나뉘어져 있어서 각자 복사, 붙여넣기해서 글자수를 세고 있는데요.
업로드 페이지 내부에서 본문 글자수가 얼마나 되나 알고 싶어요.
분량이 적절한지 파악하는데에 도움이 될 것 같아요.

**Comment by kayk1m** [comment]
@kjsik11 만들어주세요

**Comment by kjsik11** [comment]
확인 후 리뷰 부탁드립니다.

**Comment by ekf1121** [comment]
@kjsik11  부스 편집 페이지에서는 아직 안보입니다. 

![image](https://user-images.githubusercontent.com/83440232/117902561-aee0a400-b308-11eb-9538-ba9d89699bc2.png)

**Comment by kayk1m** [comment]
아무래도 저한테 얘기하고 싶었던 것 같은데,,, 이번 주 안에 추가될 것 같아요!

**Comment by kayk1m** [comment]
추가되었어요 :)
