### ISSUE TITLE
[홈]-[작품] 사파리환경에서 '가격낮은순' '가격높은순' 글자 넘침

### ISSUE THREAD

**Issue by minhyun424** [ondisplay/collected-issues#38]
breakpoint 640~ 전부 넘칩니다. 사진 첨부하겠습니다.

![스크린샷 2021-05-13 오전 11 30 09](https://user-images.githubusercontent.com/76416541/118069564-60520900-b3df-11eb-8cc7-9c804e214378.png)
![스크린샷 2021-05-13 오전 11 30 28](https://user-images.githubusercontent.com/76416541/118069572-62b46300-b3df-11eb-93d8-4cab8a6560f3.png)

**Comment by kayk1m** [comment]
http://222.112.43.54:3000/artwork?sort=min_price

여기서 한번 봐주실래요?

**Comment by minhyun424** [comment]
오 사파리로 안넘치네요 모든 breakpoint에서말이죠

**Comment by kayk1m** [comment]
그럼 이대로 올릴게요

**Comment by minhyun424** [comment]
넵! 감사합니다! 그리고 저 링크에서는 뒤로가기했을떄 정렬이 리셋되는 이슈가 없는것같아요...

**Comment by kayk1m** [comment]
노트북 문제인듯 ㅜ

**Comment by minhyun424** [comment]
잡스쉑...
