### ISSUE TITLE
[작품목록] 아이폰12 미니-사파리에서 판매중 글자크기 문제발생

### ISSUE THREAD

**Issue by minhyun424** [ondisplay/collected-issues#41]
![KakaoTalk_Image_2021-05-13-12-04-03](https://user-images.githubusercontent.com/76416541/118071887-a7da9400-b3e3-11eb-9046-92a6c3dbc44d.png)

아이폰12 미니 사파리에서만 발생
아이폰12,맥북프로16,아이패드프로12.9 사파리에서서는 문제 없음

**Comment by kayk1m** [comment]
이거 일단 킵할게요

**Comment by minhyun424** [comment]
넵!

**Comment by minhyun424** [comment]
![KakaoTalk_Image_2021-05-13-14-11-26](https://user-images.githubusercontent.com/76416541/118080657-6fdc4c80-b3f5-11eb-882a-4c60dabdeace.png)

...(아이폰 12에서도 발생했어요)

**Comment by minhyun424** [comment]
노트9 삼성 인터넷에서도 발생했어요

**Comment by kayk1m** [comment]
해결완료 빌드중

**Comment by kayk1m** [comment]
이거 해결됐는지 확인 후 닫아주세요

**Comment by minhyun424** [comment]
![Screenshot_20210513-152023_Samsung Internet](https://user-images.githubusercontent.com/76416541/118086578-27c22780-b3ff-11eb-9f4e-3bdea4898547.jpg)

 갤럭시에서는 글자 높이가 다르네요... 이부분도 혹시 해결 가능한지...

**Comment by kayk1m** [comment]
아뇨 애초에 같기가 힘든 구조인것같은데 두개가 동일선상에있는게아니라

**Comment by kayk1m** [comment]
figma대로 margin/padding이 되어있지 않은 부분이 있으면 그건 고쳐볼수있겠지만.. 글자 수직높이에있어서는 안맞는 케이스가 워낙 많았어서

**Comment by minhyun424** [comment]
오 그렇군요... 이해했어요... 글만있는거랑 저 체크박스인풋과 글 같이있는거랑 다르니까요...

**Comment by kayk1m** [comment]
모든 브라우저에서 차이가 나는거면 강제로 조정할수있겠지만 브라우저마다 다르면 좀...ㅜ

**Comment by minhyun424** [comment]
오우 그렇군요... 어려운문제구만...
