### ISSUE TITLE
배너 이미지 border radius가 적용되지 않음

### ISSUE THREAD

**Issue by ghost** [ondisplay/collected-issues#45]
배너 이미지 border radius가 적용되지 않았어요

iPad Pro 4th 12.9, Safari 에서만 확인된 문제이고, 다른 환경에서는 발견하지 못했습니다.

![image](https://user-images.githubusercontent.com/82503054/118073680-4fa59100-b3e7-11eb-880e-befbd8bfd78b.png)

**Comment by kayk1m** [comment]
이거 지금도 그러나요?

방금 머 바꾸긴했는데 확인할 방법이없음

**Comment by ghost** [comment]
해결됐어요~

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/82503054/118073941-e70ae400-b3e7-11eb-8339-7ddad1da7721.png)
근데 부스 페이지에서도 같은 문제가 있었네요

**Comment by kayk1m** [comment]
이거는 다른 이슈로 파고 일단 킵하는걸로해요 기기를 옆에 두고 고쳐야할듯
