### ISSUE TITLE
[홈]-[작품] cover과 contain view의 아이콘이 반대로 적용되어있습니다.

### ISSUE THREAD

**Issue by minhyun424** [ondisplay/collected-issues#46]
![스크린샷 2021-05-13 오후 1 54 34](https://user-images.githubusercontent.com/76416541/118079322-f3486e80-b3f2-11eb-8285-514aada69ffd.png)
![스크린샷 2021-05-13 오후 1 54 42](https://user-images.githubusercontent.com/76416541/118079324-f5123200-b3f2-11eb-8ce2-a602949cb54d.png)

(우측 상단 아이콘 참고)

다시 적용 부탁합니다.

**Comment by kayk1m** [comment]
빌드중
