### ISSUE TITLE
[헤더] desktop dropdown 수정 필요

### ISSUE THREAD

**Issue by minhyun424** [ondisplay/collected-issues#47]
![스크린샷 2021-05-13 오후 2 16 54](https://user-images.githubusercontent.com/76416541/118081323-16285200-b3f6-11eb-83ae-6f26cd6afadd.png)
![스크린샷 2021-05-13 오후 2 17 07](https://user-images.githubusercontent.com/76416541/118081325-17f21580-b3f6-11eb-9445-23d63e2d0cb1.png)

위: 서비스 캡쳐
아래: 피그마 파일

피그마파일과 동일하게 부탁드립니다.

**Comment by kayk1m** [comment]
이거 지금 당장 못해요 일부러 안한거임

**Comment by minhyun424** [comment]
넵! 확인했습니다!

**Comment by kjsik11** [comment]
수정완료
