### ISSUE TITLE
최근 본 들어갈 때 unexpected 에러 발생

### ISSUE THREAD

**Issue by ghost** [ondisplay/collected-issues#49]
모바일 데스크톱에서 동일한 증상 확인
@Jeonghyun-Kim

**Comment by kayk1m** [comment]
로그인 / 비로그인 (로그인시 이메일주소)
브라우저 / 사용 기기

적어주세요

**Comment by ghost** [comment]
로그인 skssms@kakao.com

iPhone 12 mini / safari
windows laptop / chrome
