### ISSUE TITLE
limited edition 입력이 안됨

### ISSUE THREAD

**Issue by ghost** [ondisplay/collected-issues#52]
admin 사이트에서 작품 등록시 limited edition 선택과 limited edition 개수 입력이 안됨

**Comment by kjsik11** [comment]
일단 잘 되는걸로 확인되는데 어떤 경우에 안되는지 자세히 알려주실수 있나요?

**Comment by kayk1m** [comment]
windows10 + chrome 인가요?

**Comment by ghost** [comment]
window 10+chrome 맞구요, 

 limited edition 클릭한 다음에 에디션 개수를 입력할 때 한 자리 숫자는 써지는데, 두자리 숫자가 안써지네요.

**Comment by kjsik11** [comment]
슬랙 확인 부탁드릴게용

**Comment by ghost** [comment]
넵, 확인했습니다.
