### ISSUE TITLE
구매요청 이후, 결제 이전에 작품 가격이 변동됐을 경우 결제창에서 바뀐  가격이 반영되지 않음

### ISSUE THREAD

**Issue by ghost** [ondisplay/collected-issues#53]
구매자(상우 형)이 최연재 작가의 20만원짜리 작품을 구매요청했는데 작가에게 구매요청 사실을 전달하기 전에 작가가 작품가격을 25만원으로 올리는 일어나기 어려운 일이 발생했습니다..
작가와 구매자 사이에서 조율하여 25만원에 구매하기로하고 작품 구매를 진행하였는데 결제 창에서 바뀐 금액이 적용되지 않는다고 구매자측의 연락이 왔습니다. 이 케이스는 따롭 계좌이체를 직접 받는 방향으로 해결했고, 다시 일어나지 않게 하려면 어떤 식으로 하는게 좋을지 의견 남겨주세요

![image](https://user-images.githubusercontent.com/82503054/120878515-f6044100-c5f7-11eb-86bc-a98366435912.png)
![image](https://user-images.githubusercontent.com/82503054/120878519-f8ff3180-c5f7-11eb-81f6-3c31ff5e2dc7.png)

@Jeonghyun-Kim

**Comment by kjsik11** [comment]
작가가 우리에게 말해줘서 수정을 통해 직접 DB상의 작품 가격을 변경하는 경우라면 구매요청부분의 작품 정보도 같이 바꾸게하는 방법이 있을꺼 같은데 위의 경우처럼 구매자와 작가 둘이서 가격을 협의해서 작품 구매를 진행하는 상황이라면 계좌이체의 방법밖에 없어보임..
