### ISSUE TITLE
[작가 페이지] 워딩 변경

### ISSUE THREAD

**Issue by minhyun424** [ondisplay/collected-issues#58]
<img width="1277" alt="스크린샷 2021-07-16 오후 4 28 35" src="https://user-images.githubusercontent.com/76416541/125926611-c20139b0-c4bd-46d9-aa11-89fd38cc5469.png">

헤더의 버튼을 '작품관리'로 워딩을 바꿨지만 버튼은 작가페이지입니다.
하나로 통일하는게 좋을듯

**Comment by kjsik11** [comment]
수정완료
