### ISSUE TITLE
[결제관리 페이지] 입금 기한을 만들어주세요

### ISSUE THREAD

**Issue by Dolmeng2** [ondisplay/collected-issues#63]
작가 계좌로 당일 입금할 수있도록 하는 것이 좋겠습니다.

주문 후 입금기한은 24시간입니다. 기한 내에 입금확인이 되실 경우에 결제가 정상적으로 처리되며, 
미입금시 해당 주문은 취소처리됩니다.

**Comment by Dolmeng2** [comment]
24시간 아니면 3일로 하자 (아시아프가 3일임)

**Comment by kjsik11** [comment]
프로그램 구조상 자동으로 하는게 불가능할꺼같은데 일단 정현이한테 물어보고 가능하면 진행 해봄

**Comment by kayk1m** [comment]
그냥 입금기한을 띄워두고 관리자 혹은 작가가 수동으로 닫는거라고하면 일단은 문제가 없을 것 같아요

**Comment by kjsik11** [comment]
그 방향으로 개발 하나용?
