### ISSUE TITLE
[CSV출력 페이지 이미지 왜곡]

### ISSUE THREAD

**Issue by Dolmeng2** [ondisplay/collected-issues#67]
![image](https://user-images.githubusercontent.com/87738065/129658697-94218c98-7247-4b23-ba1c-0453044a316f.png)

작가페이지에서 CSV 출력을 할 때에 이미지들이 세로로 길쭉하게 변하는 문제가 있습니다.

**Comment by kjsik11** [comment]
의심가는 부분을 고치긴 했는데 제 눈으로는 뭐가 찌그러졌는지 잘 모르겠어서 확인은 못하겠어요 확인해주세요...

**Comment by Dolmeng2** [comment]
> 의심가는 부분을 고치긴 했는데 제 눈으로는 뭐가 찌그러졌는지 잘 모르겠어서 확인은 못하겠어요 확인해주세요...

확인했어요 이제 안찌그러져요 ㅎㅎㅎ 굿굿굿


![image](https://user-images.githubusercontent.com/87738065/130376841-5717e1fd-b8bd-41a4-9e10-2471efaf12c2.png)
