### ISSUE TITLE
[작품 등록 페이지 오류] 작품상세컷을 업로드하고 수정이 정상적으로 되었지만 보이지 않음

### ISSUE THREAD

**Issue by Dolmeng2** [ondisplay/collected-issues#68]
![image](https://user-images.githubusercontent.com/87738065/129843539-0499d994-93fd-4258-bcd1-0f38b6d3bbab.png)

👇작품이 정상적으로 등록되었으나, 작품 상세 페이지에서는 대표사진만 보이고 디테일샷은 모두 누락되어 보임.

![image](https://user-images.githubusercontent.com/87738065/129843627-7973c7c3-73c1-447c-8130-ef2efdc87c50.png)

**Comment by kjsik11** [comment]
작품 디테일 이미지를 사용하는 날이 올 때 까지 임의로 숨겨놓음

**Comment by Dolmeng2** [comment]
> 작품 디테일 이미지를 사용하는 날이 올 때 까지 임의로 숨겨놓음

ㅇㅋㅇㅋㅇ 그럼 대표이미지만 사용하도록 하겠음!
